### PR TITLE
12 improve casioreq processing loop

### PR DESCRIPTION
**Pull request by zx-ncoderz**

### CODE REVIEW

**Comment by rsta2** [comment]
Why do you send a (big) pull request (for the 2nd time) without a description and close it again immediately?

**Comment by zx-ncoderz** [comment]
Sorry, I made a mistake and it seems the PRs cannot be deleted. Please ignore them.

I've been developing an add-on for the old ZX Spectrum computer to display video via the PI's HDMI port. It uses SMI to sample the Spectrum's data bus and some memory control lines to build the screen without the need for an FPGA or CPLD.

In the process I've done quite a bit of playing around with SMI, and I would have some PR's that might improve the current Circle implementation, but it's only a hobby project and I haven't got the changes in a good state yet.

Yesterday I re-arranged my code so the main code is no longer in a fork of Circle, so I should not make the PR mistake again.

Sorry for the inconvenience and thank you so much for the amazing Circle OS!!!

**Comment by rsta2** [comment]
I understand, no problem. Yes, developing the source code for Circle changes often requires additional effort to reach a reasonable level of quality. Thank you for appreciating Circle!

**Comment by zx-ncoderz** [comment]
Hi Rene,

Sorry, I made a mistake and it seems the PRs cannot be deleted. Please
ignore them.

I've been developing an add-on for the old ZX Spectrum computer to display
video via the PI's HDMI port. It uses SMI to sample the Spectrum's data bus
and some memory control lines to build the screen without the need for an
FPGA or CPLD.
In the process I've done quite a bit of playing around with SMI, and I
would have some PR's that might improve the current Circle implementation,
but it's only a hobby project and I haven't got the changes in a good state
yet.

Yesterday I re-arranged my code so the main code is no longer in a fork of
Circle, so I should not make the PR mistake again.

Sorry for the inconvenience and thank you so much for the amazing Circle
OS!!!

Richard

**Pull request closed without merging**
